---
resource_group:
  name: key-vault-rg
  location: australiaeast
key_vaults:
  primary:
    key_vault:
      name: key-vault-primary
      enabled_for_disk_encryption: true
      enabled_for_template_deployment: true
      soft_delete_retention_days: 90
      purge_protection_enabled: false
      sku_name: standard
    access_policies:
      user: []
      group:
        - Name: testkv
          key_permissions:
            - Get
            - List
          secret_permissions:
            - Get
            - List
          certificate_permissions:
            - Get
            - Import
            - List
      application:
        - Name: testkv2
          key_permissions:
            - Get
            - List
          secret_permissions:
            - Get
            - List
          certificate_permissions:
            - Get
            - Import
            - List
